### ISSUE TITLE
RepositoryEvaluator: use exception to control flow

### ISSUE THREAD

**Issue by baranowb** [jboss-set/pull-request-processor#62]
try {
            StreamComponent streamComponent =  aphrodite.getComponentBy(pullRequest.getRepository().getURL().toURI(), pullRequest.getCodebase());
            data.setAttributeValue(Attributes.REPOSITORY, new LinkData(streamComponent.getName(), repository.getURL()));
        } catch (Exception e) {
            data.setAttributeValue(Attributes.REPOSITORY, new LinkData(pullRequest.getRepository().getURL().getPath(), repository.getURL()));
        }
    }

**Comment by soul2zimate** [comment]
Fixed in https://github.com/jboss-set/pull-request-processor/commit/80a055a4d49bfc0556cc33939ae5bf3767b9a32d
