### ISSUE TITLE
Fix command line switches, some dont work

### ISSUE THREAD

**Issue by baranowb** [jboss-set/pull-request-processor#63]
-s https://github.com/jboss-set/pull-request-processor/blob/master/src/main/java/org/jboss/pull/processor/Main.java#L86

**Comment by soul2zimate** [comment]
Which option does not work ? Can you elaborate a little more?

**Comment by baranowb** [comment]
"Fix streams (-s) command line switch, it is being ignored at the moment. to Fix command line switches, some dont work " :) changed it to be more generic but I dont think more are faulty.

**Comment by soul2zimate** [comment]
it's not ignored "-s", "--streams" is the stream name in provided jboss-streams.json which allows to retrieve all repositories in this input stream.

The other  "-as", "--allowed-streams" is about the label stream name on Github PR list it's going to set

**Comment by baranowb** [comment]
Ops, my bad, I meant: -Dstreams.json Ithink.

**Comment by soul2zimate** [comment]
I think this can be closed. Parameters are revised as https://github.com/jboss-set/pull-request-processor/blob/pull-processor-0.8.0.Final/README.md
