### ISSUE TITLE
ACtionContext.write vs Main.dryRun - ambiguity in meaning of variables

### ISSUE THREAD

**Issue by baranowb** [jboss-set/pull-request-processor#64]
dryRun = false translates int write = false - completely changing meaning of passed value.

**Comment by soul2zimate** [comment]
fixed by https://github.com/jboss-set/pull-request-processor/commit/1a8f7c2ee548eb3663f5292dd98080cce78d8aa7 and https://github.com/jboss-set/pull-request-processor/commit/09cf18c4bdf158225b4c0daae9b4b99b6f7294e6
only use the dryRun option, default to false.
