### ISSUE TITLE
Wrong labels set vs branch: https://github.com/jbossas/wildfly-core-eap/pull/258

### ISSUE THREAD

**Issue by baranowb** [jboss-set/pull-request-processor#75]
branch 2.1.x, label set by user 2.x

**Comment by soul2zimate** [comment]
It needs to talk with Brian, its his choice to manually add 2.x label on downstream PR. 
It's not set by pull-request-processor. pull-request-processor will set 2.1.x to them.
I will leave this open until pull-request-processor runs against 2.1.x branch, then we can remove all 2.x labels.

**Comment by soul2zimate** [comment]
wildfly-core-eap 2.1.x is out of date.
