### ISSUE TITLE
Check upstream JIRA/PR and mark current accordingly

### ISSUE THREAD

**Issue by baranowb** [jboss-set/pull-request-processor#78]
Just sanity issue. We might have it already.

Once PR metadata is finalized add checks on upstream and in case it has been merged/resolved add proper label. Pair up with PR metadata.
Ensure proper branch and repo are being used.

**Comment by baranowb** [comment]
JIRA might not be relevant in this picture?

**Comment by baranowb** [comment]
@NOTE: just add "rejected", we already check for merge.

**Comment by wolfc** [comment]
I think https://github.com/jbossas/jboss-eap7/pull/2863#event-1952663740 qualifies as a bad positive.

It should not be `Upstream merged` but `Bad upstream PR`.

**Comment by soul2zimate** [comment]
Implemented in https://github.com/jboss-set/pull-request-processor/pull/92
