### ISSUE TITLE
Add report action to PR processor.

### ISSUE THREAD

**Issue by baranowb** [jboss-set/pull-request-processor#81]
Consider:
Create something like old PR had, so each tick will have more than a console trace from SetLabalsAction. Either https://github.com/jboss-set/pull-request-processor/blob/master/src/main/java/org/jboss/set/pull/processor/impl/action/SetLabelsAction.java#L96 or implement already present stub ReportAction (or both).

**Comment by soul2zimate** [comment]
As a label manipulator, I think we can just write down the logs of label updates into disk.
If someone likes to check PR general state, go to https://thunder.sin2.redhat.com/prbz-overview/streamview/pullrequestoverview?streamName=jboss-eap-7.1.z&componentName=jbossas-jboss-eap7

**Comment by baranowb** [comment]
I'd envision this similar to overview but with detail about current->upstream PR, labels should be enough - though it might need some tinkering in order to give best result.

**Comment by soul2zimate** [comment]
Example report result on thunder https://thunder.sin2.redhat.com/jenkins/view/SET%20Tools/job/pull-request-processor-7.2.z/ws/report.html
