### ISSUE TITLE
Add "No issue required"

### ISSUE THREAD

**Issue by soul2zimate** [jboss-set/pull-request-processor#93]
Just like `No upstream required` indicating there is no upstream needed, add something like `No issue required` to allow no issue pull request to pass the pull-request-processor checking.

For example, CP version bump pull request for next development.

**Comment by parsharma** [comment]
@soul2zimate If you are not working on this, could I give it a try?

**Comment by soul2zimate** [comment]
sure, you can take it. if you work with your own accounts rather than SET accounts, please make sure test with `-w false`. Thanks

**Comment by soul2zimate** [comment]
implemented in https://github.com/jboss-set/pull-request-processor/commit/111ad9e9341dc554ae9d46460b676f2711a8d68b via https://github.com/jboss-set/pull-request-processor/pull/95
