### ISSUE TITLE
Add "Upstream PR not required"

### ISSUE THREAD

**Issue by spyrkob** [jboss-set/pull-request-processor#96]
Add a label to represent a situation where Upstream Issue is required for tracking but we can't open Upstream Issue yet (eg CUs between 7.3.8 and 7.4.1 while 7.4.0 is not GA).

PR processor should enforce Upstream Issue link, but ignore missing Upstream PR.

**Comment by soul2zimate** [comment]
implemented in https://github.com/jboss-set/pull-request-processor/commit/121f16a283706fd1988994d3f0e34cf6ab07a3fb via https://github.com/jboss-set/pull-request-processor/pull/97
